routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use Illuminate\Foundation\Application;
use Illuminate\Support\Facades\Route;
use Inertia\Inertia;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('welcome');

Route::get('about',function (){
    return view('about');
})->name('about');

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__.'/client_auth.php';

## Admin Routes
Route::prefix('admin')->group(function (){

    Route::middleware('auth')->group(function () {
        Route::get('/', [\App\Http\Controllers\AdminController::class, 'dashboard'])->name('admin.dashboard');
        Route::get('/operacional', [\App\Http\Controllers\OperacionalController::class, 'navigation'])->name('admin.operacional');
        Route::get('/rental/ajax/details/{rentalId}', [\App\Http\Controllers\OperacionalController::class, 'rentalDetails'])->name('admin.rental');
        Route::post('/rental/ajax/update/{rentalId}', [\App\Http\Controllers\OperacionalController::class, 'rentalUpdate'])->name('admin.rental-update');
    });

    require __DIR__.'/auth.php';

});

## Cliente Routes
Route::prefix('client')->middleware('auth:client')->group(function (){

    // Dashboard
    Route::get('dashboard',[\App\Http\Controllers\ClientDashboardController::class,'dashboard'])->name('client.dashboard');

    // Locações
    Route::get('rentals',[\App\Http\Controllers\RentalsController::class,'rentals'])->name('client.rentals');

    // Locações
    Route::get('rentals/{id}',[\App\Http\Controllers\RentalsController::class,'details'])->name('client.rental');

    // Marketplace
    Route::get('marketplace',[\App\Http\Controllers\MarketplaceController::class,'navigation'])->name('client.marketplace');

    // Detalhes do item - esta rota é o conteúdo interno do Drawer
    Route::get('marketplace/item/{id}',[\App\Http\Controllers\MarketplaceController::class,'ajaxDetailItem'])->name('client.marketplace.item');

    // Cart
    Route::prefix('cart')->middleware('auth')->group(function () {

        // Index
        Route::get('/', [\App\Http\Controllers\CartController::class, 'index'])->name('cart.index');

        // Form - Remove
        Route::delete('/remove/{cartItem}', [\App\Http\Controllers\CartController::class, 'destroy'])->name('cart.destroy');

        // Ajax - Add
        Route::post('/ajax/add', [\App\Http\Controllers\CartController::class, 'store'])->name('cart.add');

        // Ajax Update
        Route::put('/ajax/update', [\App\Http\Controllers\CartController::class, 'ajaxUpdate'])->name('cart.update');

        // Ajax - Get Totals
        Route::get('ajax/total',[\App\Http\Controllers\CartController::class,'ajaxTotal'])->name('cart.ajax.total');

    });

    Route::prefix('checkout')->middleware('auth')->group(function(){

        // Configuração das datas e dias
        Route::get('/', [\App\Http\Controllers\CheckoutController::class, 'index'])->name('checkout.index');

        // Reset em uma data de item do carrinho
        Route::get('clean-item-date/{id}',[\App\Http\Controllers\CheckoutController::class,'cleanItemDate'])->name('checkout.clean-item-date');

        // Atualização do carrinho Data e Dias
        Route::post('/update', [\App\Http\Controllers\CheckoutController::class, 'checkoutUpdate'])->name('checkout.update');

        // Tela para revisão do pedido
        Route::get('/confirmation', [\App\Http\Controllers\CheckoutController::class, 'checkoutAction'])->name('checkout.confirmation');

        // Processamento da locação
        Route::get('/confirmation/accepted', [\App\Http\Controllers\CheckoutController::class, 'checkoutAccepted'])->name('checkout.accepted');

    });

});

app/Models/Cart.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Cart extends Model
{

    protected $fillable = ['user_id'];

    public function user()
    {
        return $this->belongsTo(Client::class);
    }

    public function items()
    {
        return $this->hasMany(CartItem::class);
    }

}

app/Models/Client.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'email',
        'phone',
        'address',
    ];

}

app/Http/Controllers/CartController.php
<?php

namespace App\Http\Controllers;

use App\Models\Cart;
use App\Models\CartItem;
use App\Services\CartService;
use Illuminate\Http\Request;

/**
 * Class CartController
 * Preparação dos itens para locação
 *
 * @package App\Http\Controllers
 */
class CartController extends Controller
{

    /**
     * Index
     * Carrinho de compras
     *
     * @param CartService $cartService
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Foundation\Application
     */
    public function index(CartService $cartService)
    {
        $cart = $cartService->getCart();
        $items = $cartService->getCartItems();

        return view('client.cart.index', compact('cart', 'items'));
    }

    /**
     * Store
     * Adicionar um item no Carrinho
     *
     * @param Request $request
     * @param CartService $cartService
     * @return \Illuminate\Http\JsonResponse
     */
    public function store(Request $request, CartService $cartService)
    {
        $request->validate([
            'item_id' => 'required|exists:items,id',
            'quantity' => 'required|integer|min:1',
        ]);

        $cartService->addItemToCart($request->item_id, $request->quantity);

        return response()->json([
            'message' => 'success',
        ]);
    }

    /**
     * Destroy
     * Excluir um item do carrinho
     *
     * @param CartItem $cartItem
     * @param CartService $cartService
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(CartItem $cartItem, CartService $cartService)
    {
        if($cartService->removeItemFromCart($cartItem->id)) {
            return redirect()->route('cart.index');
        }
        return redirect()->route('cart.index');
    }


    /**
     * Ajax Total
     * Retorna o total e subtotal do carrinho para atualização de UI
     *
     * @param CartService $cartService
     * @return array
     */
    public function ajaxTotal( CartService  $cartService ){

        // Total de itens no carrinho
        $itens = $cartService->getItemCount();

        // Subtotal dos itens
        $subtotal = $cartService->getItemsSubtotal();

        return [
            'total' => $itens,
            'subtotal' => $subtotal,
        ];

    }

    /**
     * Ajax Update
     * Recebe via ajax a atualização de quantidades de um equipamento do carrinho
     *
     * @param CartService $cartService
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function ajaxUpdate( CartService $cartService, Request $request )
    {
        $itemId = $request->input('item_id');
        $quantity = $request->input('quantity');

        $response = $cartService->updateItemQuantity($itemId, $quantity);

        return response()->json([
            'message' => $response
        ]);
    }

}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

app/View/Components/ClientAppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class ClientAppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('client.layouts.default');
    }
}

app/View/Components/LayoutClientHeader.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class LayoutClientHeader extends Component
{

    public $menu;

    public function __construct( $menu )
    {
        $this->menu = $menu;
    }

    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('client.layouts.partials.header');
    }
}

resources/views/client/cart/index.blade.php
<x-client-app-layout>

@inject('cartService', 'App\Services\CartService')

<!-- Main Content Wrapper -->
    <main class=" w-full px-[var(--margin-x)] pb-8">

        <x-layout-client-header menu="cart"/>

        <div class="p-3"> </div>


        <div class="container">
            <div class="text-4xl pl-3 pb-3 font-light opacity-50">Novo Pedido</div>
        </div>

        <div class="border-b mb-4 mt-5"></div>




        {{--    <div class="text-sm  text-center text-gray-500 border-b border-gray-200 dark:text-gray-400 dark:border-gray-700">
                <ul class="flex flex-wrap -mb-px container">
                    <li class="mr-2">
                        <a href="{{ route('cart.index') }}" class=" @if( !request()->has('categoryId') or request()->get('categoryId')=='all' ) tab-active @else tab-default @endif">Itens</a>
                    </li>
                </ul>
            </div>--}}
        <div class="container">

            <div class="">


                @if(!count($items))
                    <div class="p-3 text-base">Ainda não há itens no seu pedido</div>

                    <a href="{{ route('client.marketplace') }}" class="pl-3 text-sm text-gray-400">Voltar o marketplace</a>
                @endif
                @if(count($items))

                    <div class="min-h-[70vh]">
                        <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">

                            <tbody>
                            @foreach($items as $item)
                                <tr class="bg-white dark:bg-gray-800 border-b">
                                    <td class="px-1 py-4 w-[50px]">
                                        <img src="{{ asset( 'images/' . $item['item']['thumbnail']) }}" class=" max-w-[100px] m-auto max-h-[80px] h-max rounded-lg">
                                    </td>
                                    <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">

                                        <div class="text-sm mb-1 text-gray-800">
                                            {{ $item['item']['name'] }}
                                        </div>
                                        <div class="text-gray-400">
                                            <dl class="grid grid-cols-4 gap-2 text-xs ">
                                                <dt class=" font-normal">SKU</dt>
                                                <dd class="col-span-3 ">{{ $item['item']['product_sku']}}</dd>
                                            </dl>
                                            <dl class="grid grid-cols-4 gap-2 text-xs ">
                                                <dt class="font-normal">Vlr. Unit</dt>
                                                <dd class="col-span-3 ">R$ {{ \App\Services\General::currencyFormatter( $item['item']['daily_rental_price'] ) }}</dd>
                                            </dl>
                                            <dl class="grid grid-cols-4 gap-2 text-xs ">
                                                <dt class="font-normal">Estoque</dt>
                                                <dd class="col-span-3 ">
                                                    {{ $item['item']->availableUnits() }}</dd>
                                            </dl>
                                        </div>

                                    </th>
                                    <td class="px-6 py-4">

                                        <div class="uppercase text-xs mb-1">Quantidade</div>
                                        <div x-data="window.cartItemManager({{ $item['item']['id'] }}, {{ $item->quantity }})">

                                            <input type="text"
                                                   class="bg-gray-50 border text-center border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                                                   x-model="quantity"
                                                   x-debounce="500"
                                                   @input="updateQuantity">
                                        </div>

                                    </td>
                                    <td class="px-6 py-4 text-end">


                            <form action="{{ route('cart.destroy', $item->id) }}" method="POST">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="px-3 py-2 text-xs   text-center text-rose-800 bg-rose-50  rounded-lg hover:bg-rose-800 focus:ring-4 focus:outline-none focus:ring-rose-300 dark:bg-rose-600 dark:hover:bg-rose-700 dark:focus:ring-rose-800">X</button>
                            </form>

                                    </td>
                                </tr>

                            @endforeach

                            </tbody>
                        </table>
                    </div>

                    <div class="grid grid-cols-2 gap-5 border-t pt-4">
                        <div>
                            <a href="{{ route('client.marketplace') }}" class="text-gray-900 bg-white hover:bg-gray-100 border border-gray-200 focus:ring-4 focus:outline-none focus:ring-gray-100  rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center dark:focus:ring-gray-600 dark:bg-gray-800 dark:border-gray-700 dark:text-white dark:hover:bg-gray-700 mr-2 mb-2">
                                Voltar ao marketplace
                            </a>
                        </div>
                        <div class="text-center">
                            <a  href="{{ route('checkout.index') }}"  class="text-white w-full block bg-blue-700 w-full hover:bg-blue-800 focus:ring-4 focus:ring-blue-300  rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">
                                Continuar
                            </a>
                        </div>
                    </div>
                @endif

            </div>


        </div>


</x-client-app-layout>